"""
Kane AI test suite for LambdaTest eCommerce playground.
Generated by CI pipeline. Do not edit manually.
Each test runs a Kane CLI objective against the live site.
"""

import json
import shutil
import subprocess
import pytest


def _run_kane(objective: str, url: str, timeout: int = 120) -> dict:
    kane = shutil.which("kane-cli") or "kane-cli"
    result = subprocess.run(
        [kane, "run", objective, "--url", url, "--agent", "--headless", "--timeout", str(timeout)],
        capture_output=True,
        text=True,
        check=False,
    )
    for line in reversed(result.stdout.splitlines()):
        line = line.strip()
        if line:
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue
    return {
        "status": "failed",
        "one_liner": result.stderr.strip() or "Kane CLI produced no parseable output",
        "link": "",
    }

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_navigate_to_products_and_view_list():
    """SC-001: Navigate to products section and view available product list."""
    result = _run_kane(
        "User can navigate to the products section of the site and view a list of available products",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=120,
    )
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_filter_products_by_category():
    """SC-002: Filter products by category."""
    result = _run_kane(
        "User can use filters (e.g., rewards, travel, cashback) to refine results",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=120,
    )
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_click_product_view_details():
    """SC-003: Click a product to view details including price and description."""
    result = _run_kane(
        "User can click on a product to view details",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=180,
    )
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_product_highlights_visible_without_login():
    """SC-004: View product highlights without logging in."""
    result = _run_kane(
        "User can see clear card comparison or highlights without logging in",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=120,
    )
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_relevant_results_for_selected_filter():
    """SC-005: Search results are relevant to selected filters or criteria."""
    result = _run_kane(
        "User receives relevant results based on selected filters or search criteria",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=120,
    )
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")
