"""
Kane AI test suite for LambdaTest eCommerce playground.
Generated by CI pipeline. Do not edit manually.
Each test runs a Kane CLI objective against the live site.
"""

import json
import shutil
import subprocess
from pathlib import Path
import pytest


def _run_kane(objective: str, url: str, timeout: int = 120) -> dict:
    kane = shutil.which("kane-cli") or "kane-cli"
    result = subprocess.run(
        [kane, "run", objective, "--url", url, "--agent", "--headless", "--timeout", str(timeout)],
        capture_output=True,
        text=True,
        check=False,
    )
    for line in reversed(result.stdout.splitlines()):
        line = line.strip()
        if line:
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue
    return {
        "status": "failed",
        "one_liner": result.stderr.strip() or "Kane CLI produced no parseable output",
        "link": "",
    }


def _save_kane_result(requirement_id: str, scenario_id: str, test_case_id: str, result: dict) -> None:
    Path("reports").mkdir(exist_ok=True)
    record = {
        "requirement_id": requirement_id,
        "scenario_id": scenario_id,
        "test_case_id": test_case_id,
        "status": result.get("status", "failed"),
        "link": result.get("link", ""),
        "one_liner": result.get("one_liner", ""),
        "duration": result.get("duration"),
    }
    Path(f"reports/kane_result_{scenario_id}.json").write_text(
        json.dumps(record, indent=2), encoding="utf-8"
    )

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_navigate_to_products_and_view_list():
    """SC-001: Navigate to product catalog and view product list."""
    result = _run_kane(
        "Go to ecommerce-playground.lambdatest.io, navigate to the product catalog, and verify that a list of products is displayed",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=120,
    )
    _save_kane_result("AC-001", "SC-001", "TC-001", result)
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_filter_products_by_category():
    """SC-002: Apply a brand filter to narrow product results."""
    result = _run_kane(
        "On ecommerce-playground.lambdatest.io go to the Phones category page and click the Apple brand filter in the left sidebar to filter the product list",
        "https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=20",
        timeout=120,
    )
    _save_kane_result("AC-002", "SC-002", "TC-002", result)
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_click_product_view_details():
    """SC-003: Click a product to view its detail page."""
    result = _run_kane(
        "On ecommerce-playground.lambdatest.io click on any product in the catalog to open its detail page and verify the product name and price are shown",
        "https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=20",
        timeout=180,
    )
    _save_kane_result("AC-003", "SC-003", "TC-003", result)
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_product_highlights_visible_without_login():
    """SC-004: Browse products and homepage without logging in."""
    result = _run_kane(
        "Visit ecommerce-playground.lambdatest.io without logging in and verify that products or featured items are visible on the page",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=120,
    )
    _save_kane_result("AC-004", "SC-004", "TC-004", result)
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_relevant_results_for_selected_filter():
    """SC-005: Search for a product by name and see relevant results."""
    result = _run_kane(
        "On ecommerce-playground.lambdatest.io use the search bar to search for iPhone and verify that relevant product results are shown",
        "https://ecommerce-playground.lambdatest.io/",
        timeout=120,
    )
    _save_kane_result("AC-005", "SC-005", "TC-005", result)
    link = result.get("link", "")
    if link:
        print(f"\nKane session: {link}")
    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")
