"""
Selenium test suite for AmEx credit card browsing and search.
Generated by agentic SDLC pipeline — do not edit manually.
Each test maps to one acceptance criterion in requirements/search.txt.
"""

import pytest
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from tests.selenium.pages.credit_cards_page import CreditCardsPage


# ── TC-001 ────────────────────────────────────────────────────────────────────

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_navigate_to_credit_cards_and_view_list(driver):
    """SC-001: Navigate to credit cards section and view available card list."""
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    assert "credit-card" in page.current_url().lower() or "credit-cards" in page.current_url().lower(), \
        f"Expected credit cards URL, got: {page.current_url()}"

    card_tiles = page.get_card_tiles()
    assert len(card_tiles) > 0, "Expected at least one credit card tile to be visible on the page"


# ── TC-002 ────────────────────────────────────────────────────────────────────

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_filter_cards_by_category(driver):
    """SC-002: Filter credit cards by category (rewards, travel, cashback)."""
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    filter_chips = page.get_filter_chips()
    assert len(filter_chips) > 0, "Expected filter chips to be present on the credit cards page"

    filter_names = ["Travel", "Cash Back", "Rewards", "Featured", "Business"]
    applied = False
    for name in filter_names:
        if page.apply_filter(name):
            applied = True
            break

    assert applied, f"Could not apply any of the expected filters: {filter_names}"

    card_tiles = page.get_card_tiles()
    assert len(card_tiles) > 0, "Expected filtered card results to be displayed after applying a filter"


# ── TC-003 ────────────────────────────────────────────────────────────────────

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_click_card_view_details(driver):
    """SC-003: Click a credit card to view details including benefits, fees, and rewards."""
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    initial_url = page.current_url()
    clicked = page.click_first_card_details()
    assert clicked, "Could not find any 'View Details' link or card tile to click"

    WebDriverWait(driver, 15).until(
        lambda d: d.current_url != initial_url or len(page.get_card_benefits_elements()) > 0
    )

    benefits = page.get_card_benefits_elements()
    assert len(benefits) > 0, (
        "Expected benefits, rewards, or annual fee information on the card detail page. "
        f"Current URL: {page.current_url()}"
    )


# ── TC-004 ────────────────────────────────────────────────────────────────────

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_card_highlights_visible_without_login(driver):
    """SC-004: View card highlights and comparison without logging in."""
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    login_visible = page.is_login_button_visible()
    assert login_visible, "Expected a 'Log In' button to confirm user is not logged in"

    highlights = page.get_card_highlights()
    card_tiles = page.get_card_tiles()
    assert len(highlights) > 0 or len(card_tiles) > 0, (
        "Expected card highlights or card tiles to be visible without logging in"
    )


# ── TC-005 ────────────────────────────────────────────────────────────────────

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_relevant_results_for_selected_filter(driver):
    """SC-005: Search results are relevant to selected filters or criteria."""
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    applied = page.apply_filter("Travel")
    if not applied:
        applied = page.apply_filter("Cash Back")

    assert applied, "Could not apply Travel or Cash Back filter"

    card_tiles = page.get_card_tiles()
    assert len(card_tiles) > 0, "Expected card results after applying a filter"

    page_text = driver.find_element("tag name", "body").text.lower()
    relevant_keywords = ["travel", "cash back", "reward", "points", "miles", "platinum", "gold"]
    has_relevant_content = any(kw in page_text for kw in relevant_keywords)
    assert has_relevant_content, (
        "Expected filtered results to contain relevant keywords matching the selected filter. "
        f"Checked for: {relevant_keywords}"
    )
