import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


FUNCTION_NAMES = {
    "SC-001": "test_sc_001_navigate_to_products_and_view_list",
    "SC-002": "test_sc_002_filter_products_by_category",
    "SC-003": "test_sc_003_click_product_view_details",
    "SC-004": "test_sc_004_product_highlights_visible_without_login",
    "SC-005": "test_sc_005_relevant_results_for_selected_filter",
}


HEADER = '''"""
Kane AI test suite for LambdaTest eCommerce playground.
Generated by CI pipeline. Do not edit manually.
Each test runs a Kane CLI objective against the live site.
"""

import json
import shutil
import subprocess
from pathlib import Path
import pytest


def _run_kane(objective: str, url: str, timeout: int = 120) -> dict:
    kane = shutil.which("kane-cli") or "kane-cli"
    result = subprocess.run(
        [kane, "run", objective, "--url", url, "--agent", "--headless", "--timeout", str(timeout)],
        capture_output=True,
        text=True,
        check=False,
    )
    for line in reversed(result.stdout.splitlines()):
        line = line.strip()
        if line:
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue
    return {
        "status": "failed",
        "one_liner": result.stderr.strip() or "Kane CLI produced no parseable output",
        "link": "",
    }


def _save_kane_result(requirement_id: str, scenario_id: str, test_case_id: str, result: dict) -> None:
    Path("reports").mkdir(exist_ok=True)
    record = {
        "requirement_id": requirement_id,
        "scenario_id": scenario_id,
        "test_case_id": test_case_id,
        "status": result.get("status", "failed"),
        "link": result.get("link", ""),
        "one_liner": result.get("one_liner", ""),
        "duration": result.get("duration"),
    }
    Path(f"reports/kane_result_{scenario_id}.json").write_text(
        json.dumps(record, indent=2), encoding="utf-8"
    )

'''


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scenarios", default="scenarios/scenarios.json")
    parser.add_argument("--tests-out", default="tests/selenium/test_products.py")
    parser.add_argument("--objectives-out", default="kane/objectives.json")
    return parser.parse_args()


def load_scenarios(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return [s for s in data if s.get("status") != "deprecated"]


def build_test_function(scenario):
    function_name = FUNCTION_NAMES.get(
        scenario["id"],
        f"test_{scenario['id'].lower().replace('-', '_')}",
    )
    title = scenario["title"].replace('"', "'")
    objective = scenario["kane_objective"].replace("\\", "\\\\").replace('"', '\\"')
    url = scenario["kane_url"]
    timeout = 180 if scenario["id"] == "SC-003" else 120

    test_case_id = scenario.get("test_case_id", "TC-000")
    body = (
        f'    result = _run_kane(\n'
        f'        "{objective}",\n'
        f'        "{url}",\n'
        f'        timeout={timeout},\n'
        f'    )\n'
        f'    _save_kane_result("{scenario["requirement_id"]}", "{scenario["id"]}", "{test_case_id}", result)\n'
        f'    link = result.get("link", "")\n'
        f'    if link:\n'
        f'        print(f"\\nKane session: {{link}}")\n'
        f'    assert result.get("status") == "passed", result.get("one_liner", "Kane test failed")'
    )

    return (
        f'@pytest.mark.scenario("{scenario["id"]}")\n'
        f'@pytest.mark.requirement("{scenario["requirement_id"]}")\n'
        f'def {function_name}():\n'
        f'    """{scenario["id"]}: {title}."""\n'
        f'{body}\n'
    )


def build_objectives(scenarios):
    today = datetime.now(timezone.utc).date().isoformat()
    objectives = []
    for scenario in scenarios:
        objectives.append(
            {
                "scenario_id": scenario["id"],
                "test_case_id": scenario["test_case_id"],
                "requirement_id": scenario["requirement_id"],
                "objective": scenario["kane_objective"],
                "url": scenario["kane_url"],
                "timeout": 180 if scenario["id"] == "SC-003" else 120,
                "max_steps": 20 if scenario["id"] == "SC-003" else 15,
                "last_run_status": scenario.get("kane_last_status", "not_run"),
                "last_run_date": today if scenario.get("kane_last_status") else None,
            }
        )
    return objectives


def main():
    args = parse_args()
    scenarios = load_scenarios(args.scenarios)

    rendered = [HEADER.rstrip(), ""]
    for scenario in scenarios:
        rendered.append(build_test_function(scenario).rstrip())
        rendered.append("")

    test_output = Path(args.tests_out)
    test_output.parent.mkdir(parents=True, exist_ok=True)
    test_output.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")

    objectives = build_objectives(scenarios)
    objectives_path = Path(args.objectives_out)
    objectives_path.parent.mkdir(parents=True, exist_ok=True)
    objectives_path.write_text(json.dumps(objectives, indent=2) + "\n", encoding="utf-8")

    print(f"tests_generated={len(scenarios)} objectives_updated={len(objectives)}")


if __name__ == "__main__":
    main()
