"""
Generates .github/workflows/agentic-validate.yml for a target repo.
Three-job workflow:
  Job 1: kane-verify   — 10 parallel Kane TestMD runs against localhost
  Job 2: playwright-regression — HyperExecute matrix (Chrome + Firefox + Edge)
  Job 3: rca-summary   — parses both artifacts and writes GHA step summary
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from repo_analyzer import RepoProfile


def _build_workflow(
    repo_profile: RepoProfile,
    kane_objective: str,
    he_config_name: str = "hyperexecute-agentic.yaml",
    kane_project_id_secret: str = "KANE_PROJECT_ID",
    kane_folder_id_secret: str = "KANE_FOLDER_ID",
) -> str:
    wd = repo_profile.app_working_dir
    port = repo_profile.app_port
    node_ver = repo_profile.node_version
    install_cmd = repo_profile.install_cmd
    cache_dep_path = f"{wd}/package-lock.json" if wd else "package-lock.json"

    # Path to HE config relative to repo root (it lives inside app_working_dir)
    he_config_path = f"{wd}/{he_config_name}" if wd else he_config_name

    # HyperExecute CLI download + run path relative to repo root
    # The CLI is downloaded to repo root; app_working_dir may be a subdirectory
    depth = wd.count("/") + 1 if wd else 0
    he_cli_rel = "../" * depth + "hyperexecute" if depth > 0 else "./hyperexecute"

    workflow = textwrap.dedent(f"""\
        # Auto-generated by Agentic STLC repo-upgrade skill
        # DO NOT edit manually — re-run the skill to regenerate
        name: Agentic STLC — Feature Validation

        on:
          push:
            branches:
              - 'feature/agentic-*'
          workflow_dispatch:
            inputs:
              full_run:
                description: 'Run all tests (true) or only new/updated (false)'
                type: boolean
                default: true

        jobs:
          # ─────────────────────────────────────────────────────────────────
          # Job 1: Kane functional verification against the running localhost app
          # 10 parallel Kane CLI workers, each running one _test.md file
          # ─────────────────────────────────────────────────────────────────
          kane-verify:
            name: Kane AI Verification
            runs-on: ubuntu-latest
            timeout-minutes: 20
            defaults:
              run:
                working-directory: {wd if wd else '.'}

            steps:
              - uses: actions/checkout@v4

              - name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                  node-version: '{node_ver}'
                  cache: npm
                  cache-dependency-path: {cache_dep_path}

              - name: Install dependencies
                run: {install_cmd}

              - name: Install Playwright browsers
                run: npx playwright install --with-deps chromium

              - name: Install Kane CLI
                run: npm install -g @testmuai/kane-cli
                working-directory: ${{{{ github.workspace }}}}

              - name: Configure Kane TMS
                run: |
                  kane-cli config project ${{{{ secrets.{kane_project_id_secret} }}}}
                  kane-cli config folder  ${{{{ secrets.{kane_folder_id_secret} }}}}
                env:
                  LT_USERNAME: ${{{{ secrets.LT_USERNAME }}}}
                  LT_ACCESS_KEY: ${{{{ secrets.LT_ACCESS_KEY }}}}

              - name: Start application
                run: npm start &

              - name: Wait for app to be ready
                run: npx wait-on http://localhost:{port} --timeout 60000
                working-directory: ${{{{ github.workspace }}}}

              - name: Run Kane TestMD (10 parallel workers)
                run: |
                  mkdir -p ${{{{ github.workspace }}}}/kane_outputs
                  find ${{{{ github.workspace }}}}/kane/testmd -name '*_test.md' | \\
                    xargs -P 10 -I {{}} sh -c \\
                      'name=$(basename {{}} _test.md); \\
                       kane-cli testmd run {{}} --agent --headless \\
                         --on-lock-conflict wait --retry \\
                         2>&1 | tee ${{{{ github.workspace }}}}/kane_outputs/${{name}}.ndjson; \\
                       echo "EXIT_CODE:$?" >> ${{{{ github.workspace }}}}/kane_outputs/${{name}}.ndjson'
                env:
                  LT_USERNAME: ${{{{ secrets.LT_USERNAME }}}}
                  LT_ACCESS_KEY: ${{{{ secrets.LT_ACCESS_KEY }}}}
                working-directory: ${{{{ github.workspace }}}}

              - name: Upload Kane results and code exports
                uses: actions/upload-artifact@v4
                if: always()
                with:
                  name: kane-results
                  path: |
                    kane_outputs/
                    kane/testmd/output-*/

          # ─────────────────────────────────────────────────────────────────
          # Job 2: HyperExecute Playwright regression
          # Matrix: Chrome × Firefox × Edge — 3 parallel VMs
          # Each VM starts the app independently via tunnel
          # ─────────────────────────────────────────────────────────────────
          playwright-regression:
            name: HyperExecute Regression (Chrome / Firefox / Edge)
            runs-on: ubuntu-latest
            needs: kane-verify
            timeout-minutes: 25
            outputs:
              he_job_id: ${{{{ steps.he_run.outputs.he_job_id }}}}

            steps:
              - uses: actions/checkout@v4

              - name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                  node-version: '{node_ver}'
                  cache: npm
                  cache-dependency-path: {cache_dep_path}

              - name: Install dependencies
                working-directory: {wd if wd else '.'}
                run: {install_cmd}

              - name: Download HyperExecute CLI
                run: |
                  wget https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
                  chmod +x hyperexecute

              - name: Run HyperExecute (Chrome + Firefox + Edge in parallel)
                id: he_run
                working-directory: {wd if wd else '.'}
                run: |
                  {he_cli_rel} --user $LT_USERNAME --key $LT_ACCESS_KEY --config {he_config_name} 2>&1 | tee /tmp/he_output.log
                  JOB_ID=$(grep -oP 'jobId=\\K[\\w-]+' /tmp/he_output.log | head -1 || true)
                  echo "he_job_id=$JOB_ID" >> $GITHUB_OUTPUT
                env:
                  LT_USERNAME: ${{{{ secrets.LT_USERNAME }}}}
                  LT_ACCESS_KEY: ${{{{ secrets.LT_ACCESS_KEY }}}}

              - name: Upload Playwright reports
                uses: actions/upload-artifact@v4
                if: always()
                with:
                  name: playwright-reports
                  path: {wd + '/playwright-report/' if wd else 'playwright-report/'}

          # ─────────────────────────────────────────────────────────────────
          # Job 3: RCA — parse Kane + Playwright results, enrich via
          #         LambdaTest MCP (https://mcp.lambdatest.com/mcp)
          # ─────────────────────────────────────────────────────────────────
          rca-summary:
            name: RCA Summary
            runs-on: ubuntu-latest
            needs: [kane-verify, playwright-regression]
            if: always()

            steps:
              - uses: actions/checkout@v4

              - name: Setup Python
                uses: actions/setup-python@v5
                with:
                  python-version: '3.11'

              - name: Install RCA dependencies (MCP + HTTP)
                run: pip install mcp httpx httpx-sse

              - name: Download Kane results
                uses: actions/download-artifact@v4
                with:
                  name: kane-results
                  path: artifacts/kane-results
                continue-on-error: true

              - name: Download Playwright reports
                uses: actions/download-artifact@v4
                with:
                  name: playwright-reports
                  path: artifacts/playwright-reports
                continue-on-error: true

              - name: Run RCA parser (with LambdaTest MCP enrichment)
                run: |
                  python ci/rca_parser.py \\
                    --kane artifacts/kane-results/ \\
                    --playwright artifacts/playwright-reports/ \\
                    --output artifacts/rca_result.json \\
                    --summary $GITHUB_STEP_SUMMARY \\
                    --he-job-id "${{{{ needs.playwright-regression.outputs.he_job_id }}}}"
                env:
                  LT_USERNAME: ${{{{ secrets.LT_USERNAME }}}}
                  LT_ACCESS_KEY: ${{{{ secrets.LT_ACCESS_KEY }}}}

              - name: Upload RCA result
                uses: actions/upload-artifact@v4
                if: always()
                with:
                  name: rca-summary
                  path: artifacts/rca_result.json
    """)

    return workflow


def inject(
    repo_profile: RepoProfile,
    kane_objective: str,
    workspace_dir: str,
    he_config_name: str = "hyperexecute-agentic.yaml",
) -> str:
    """
    Write .github/workflows/agentic-validate.yml to the workspace.

    Returns the relative path to the written file.
    """
    workspace = Path(workspace_dir)
    workflows_dir = workspace / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)

    dest = workflows_dir / "agentic-validate.yml"
    content = _build_workflow(repo_profile, kane_objective, he_config_name)
    dest.write_text(content, encoding="utf-8")
    rel = str(dest.relative_to(workspace)).replace("\\", "/")
    print(f"[gha_injector] wrote {rel}")
    return rel
